sudo: false

language: php

before_install:
  - phpenv config-rm xdebug.ini || true

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - php: 5.3
      dist: precise

notifications:
  email: false

install:
  - composer install

script:
  - composer test
